package com.example.lingolenstest.detection

import android.util.SparseArray

object Labels {
    val LABELS = SparseArray<String>().apply {
        put(0, "person")
        put(1, "bicycle")
        put(2, "car")
        put(3, "motorcycle")
        put(4, "airplane")
        put(5, "bus")
        put(6, "train")
        put(7, "truck")
        put(8, "boat")
        put(9, "traffic light")
        put(10, "fire hydrant")
        put(11, "stop sign")
        put(12, "parking meter")
        put(13, "bench")
        put(14, "bird")
        put(15, "cat")
        put(16, "dog")
        put(17, "horse")
        put(18, "sheep")
        put(19, "cow")
        put(20, "elephant")
        put(21, "bear")
        put(22, "zebra")
        put(23, "giraffe")
        put(24, "backpack")
        put(25, "umbrella")
        put(26, "handbag")
        put(27, "tie")
        put(28, "suitcase")
        put(29, "frisbee")
        put(30, "skis")
        put(31, "snowboard")
        put(32, "sports ball")
        put(33, "kite")
        put(34, "baseball bat")
        put(35, "baseball glove")
        put(36, "skateboard")
        put(37, "surfboard")
        put(38, "tennis racket")
        put(39, "bottle")
        put(40, "wine glass")
        put(41, "cup")
        put(42, "fork")
        put(43, "knife")
        put(44, "spoon")
        put(45, "bowl")
        put(46, "banana")
        put(47, "apple")
        put(48, "sandwich")
        put(49, "orange")
        put(50, "broccoli")
        put(51, "carrot")
        put(52, "hot dog")
        put(53, "pizza")
        put(54, "donut")
        put(55, "cake")
        put(56, "chair")
        put(57, "couch")
        put(58, "potted plant")
        put(59, "bed")
        put(60, "dining table")
        put(61, "toilet")
        put(62, "tv")
        put(63, "laptop")
        put(64, "computer mouse")
        put(65, "remote")
        put(66, "keyboard")
        put(67, "cell phone")
        put(68, "microwave")
        put(69, "oven")
        put(70, "toaster")
        put(71, "sink")
        put(72, "refrigerator")
        put(73, "book")
        put(74, "clock")
        put(75, "vase")
        put(76, "scissors")
        put(77, "teddy bear")
        put(78, "hair drier")
        put(79, "toothbrush")
    }
}

